board/urls.py
from django.urls import path

from .views import base_views,question_views,answer_views,vote_views,category_views,bookmark_views,message_views,search_views,advertise_views,inquiry_views

app_name = 'board'



urlpatterns = [
    # base_views.py
    path('',base_views.index, name = 'index'),
    path('question/<int:question_id>/', base_views.detail, name = 'detail'),
    path('faq/',base_views.faq,name='faq'),
    path('privacy_law/',base_views.privacy_law,name='privacy_law'),
    path('using_rule/',base_views.using_rule,name='using_rule'),
    
    #category_views.py
    path('category/<str:slug>/',category_views.category_questions, name = 'category_questions'),
    path('api/categories/', category_views.get_categories_by_type, name='get_categories_by_type'),
    
    # question_views.py
    path('question/create/', question_views.question_create,name='question_create'),
    path('question/modify/<int:question_id>/',question_views.question_modify,name='question_modify'),
    path('question/delete/<int:question_id>/',question_views.question_delete,name='question_delete'),
    path('question/notice/<int:question_id>/', question_views.toggle_notice, name='toggle_notice'),
    
    path('advertisement/create/<int:question_id>', advertise_views.advertisement_create, name='advertisement_create'),
    path('advertisement/list/', advertise_views.advertisement_list, name='advertisement_list'),
    path('advertisement/modify/<int:question_id>/', advertise_views.advertisement_modify, name='advertisement_modify'),
    path('advertisement/delete/<int:question_id>/', advertise_views.advertisement_delete, name='advertisement_delete'),
    path('advertisement/approve/<int:question_id>/', advertise_views.advertisement_approve, name='advertisement_approve'),
    
    # 좋아요 view
    path('question/<int:question_id>/bookmark/', bookmark_views.bookmark_question, name='bookmark_question'),
    path('questions/bookmarked/',bookmark_views.bookmarked_questions,name='bookmarked_questions'),
    
    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create,name='answer_create'),
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify,name="answer_modify"),
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete,name='answer_delete'),
    
    path('search/', search_views.search, name='search'),
    path('search/<str:category_slug>/', search_views.category_search_results, name='category_search_results'),
    
    #vote_views.py
    path('upvote/question/<int:question_id>/',vote_views.upvote_question,name='upvote_question'),
    path('downvote/question/<int:question_id>/',vote_views.downvote_question,name='downvote_question'),
    path('upvote/answer/<int:answer_id>/',vote_views.upvote_answer,name='upvote_answer'),
    path('downvote/answer/<int:answer_id>/',vote_views.downvote_answer,name='downvote_answer'),

    
    path('messages/', message_views.message_list, name='message_list'),
    path('messages/conversation/<int:user_id>/', message_views.conversation_detail, name='conversation_detail'),
    path('messages/send/', message_views.send_message, name='send_message'),
    path('api/search-users/', message_views.search_users, name='search_users'),
    
    #문의하기
    path('inquiry/', inquiry_views.inquiry_list, name='inquiry_list'),
    path('inquiry/create/', inquiry_views.inquiry_create, name='inquiry_create'),
    path('inquiry/modify/<int:inquiry_id>/', inquiry_views.inquiry_modify, name='inquiry_modify'),
    path('inquiry/delete/<int:inquiry_id>/', inquiry_views.inquiry_delete, name='inquiry_delete'),
    
    path('inquiry/<int:inquiry_id>/', inquiry_views.inquiry_detail, name='inquiry_detail'),
    path('inquiry/<int:inquiry_id>/comment/', inquiry_views.inquiry_comment_create, name='inquiry_comment_create'),
    path('inquiry/comment/modify/<int:comment_id>/', inquiry_views.inquiry_comment_modify, name='inquiry_comment_modify'),
    path('inquiry/comment/delete/<int:comment_id>/', inquiry_views.inquiry_comment_delete, name='inquiry_comment_delete'),

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as av
from django.urls import reverse_lazy
from .views import base_views,find_views,profile_views,admin_views,auth_views,report_views

app_name = 'common'

urlpatterns = [
    # 로그인 & 아웃
    path('login/',auth_views.login_view,name='login'),
    path('logout/',auth_views.logout_view,name='logout'),

    
    path('delete-account/',auth_views.delete_account,name='delete_account'),
    
    # 회원가입 및 메일인증
    path('activate/<str:uidb64>/<str:token>/', base_views.activate, name='activate'),
    path('signup/', base_views.signup, name='signup'),
    path('get_business_types/<int:category_id>/', base_views.get_business_types, name='get_business_types'),
    
    # 프로필 수정
    path('profile/',profile_views.profile,name = 'profile'),
    path('profile/<str:username>/', profile_views.user_profile, name='user_profile'),
    path('password_change/', av.PasswordChangeView.as_view(
        template_name='common/password_change.html',
        success_url='/common/password_change/done/'
    ), name='password_change'),
    path('password_change/done/', av.PasswordChangeDoneView.as_view(
        template_name='common/password_change_done.html'
    ), name='password_change_done'),
    
    path('my-posts/',profile_views.my_posts,name='my_posts'),
    
    # ID/PW 찾기
    path('find_id/', find_views.find_id, name='find_id'),
    path('reset_password/', find_views.reset_password, name='reset_password'),
    path('reset_password_confirm/<uidb64>/<token>/', 
        av.PasswordResetConfirmView.as_view(
            template_name='common/password_reset_confirm.html',
            success_url=reverse_lazy('common:login')
        ),
        name='password_reset_confirm'),
    
# common/urls.py
    path('admin/toggle-notice/<int:question_id>/', admin_views.toggle_notice, name='toggle_notice'),
    path('admin/delete-post/<int:question_id>/', admin_views.admin_delete, name='admin_delete'),
    path('admin/restrict_user/', admin_views.restrict_user, name='restrict_user'),
    path('admin/unrestrict/',admin_views.unrestrict_user,name='unrestrict_user'),
    path('admin/toggle-advertiser/',admin_views.toggle_advertise,name='toggle_advertise'),

    path('ajax/fetch-user-info/', admin_views.fetch_user_info, name='fetch_user_info'),


    path('report/user/<str:username>/', report_views.report_user, name='report_user'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('common/',include('common.urls')),
    path('',base_views.index,name='index'),
    path('summernote/', include('django_summernote.urls')),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)) ]
    urlpatterns += [
        path('silk/', include('silk.urls', namespace='silk'))
    ]

board/views/advertise_views.py
from django.shortcuts import render, get_object_or_404,redirect
from ..models import Question, Advertisement
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from ..forms import AdvertisementForm,AdvertisementApprovalForm
from django.contrib import messages


@login_required(login_url='common:login')
def advertisement_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    if request.user != question.author or not request.user.is_advertise:
        raise PermissionDenied('광고 등록 권한이 없습니다.')
    
    if request.method == 'POST':
        form = AdvertisementForm(request.POST, request.FILES)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.question = question
            advertisement.save()
            messages.success(request, '광고가 신청되었습니다. 관리자 승인 후 게시됩니다.')
            return redirect('board:detail', question_id=question.id)
    else:
        form = AdvertisementForm()
    
    context = {
        'form': form,
        'question': question
    }
    return render(request, 'board/advertisement/advertisement_form.html', context)


@login_required(login_url='common:login')
def advertisement_modify(request, question_id):
    advertisement = get_object_or_404(Advertisement, question_id=question_id)
    
    if request.user != advertisement.question.author and not request.user.is_admin:
        raise PermissionDenied('수정 권한이 없습니다.')
        
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES, instance=advertisement)
        if form.is_valid():
            advertisement = form.save()
            return redirect('board:detail', question_id=question_id)
    else:
        form = AdvertisementForm(instance=advertisement)
    
    context = {
        'form': form,
        'question': advertisement.question
    }
    return render(request, 'board/advertisement/advertisement_form.html', context)


@login_required(login_url='common:login')
def advertisement_delete(request, question_id):
    advertisement = get_object_or_404(Advertisement, question_id=question_id)
    
    if request.user != advertisement.question.author and not request.user.is_admin:
        raise PermissionDenied('삭제 권한이 없습니다.')
    
    if request.method == "POST":
        advertisement.delete()
        messages.success(request, '광고가 삭제되었습니다.')
        return redirect('board:detail', question_id=question_id)
    
    return render(request, 'board/advertisement/advertisement_confirm_delete.html', {
        'advertisement': advertisement
    })

@login_required(login_url='common:login')
def advertisement_list(request):
    # 일반 광고주는 자신의 광고만, 관리자는 모든 광고 조회
    if request.user.is_admin:
        advertisements = Advertisement.objects.all()
    else:
        advertisements = Advertisement.objects.filter(question__author=request.user)
        
    context = {'advertisements': advertisements}
    return render(request, 'board/advertisement/advertisement_list.html', context)

@login_required(login_url='common:login')
def advertisement_approve(request, question_id):
    # question_id로 Advertisement 찾기
    advertisement = get_object_or_404(Advertisement, question_id=question_id)
    
    if not request.user.is_admin:
        raise PermissionDenied('관리자만 접근 가능합니다.')
    
    if request.method == 'POST':
        form = AdvertisementApprovalForm(request.POST, instance=advertisement)
        if form.is_valid():
            advertisement = form.save()
            messages.success(request, '광고 상태가 업데이트되었습니다.')
            return redirect('board:advertisement_list')
    else:
        form = AdvertisementApprovalForm(instance=advertisement)
    
    context = {
        'form': form,
        'advertisement': advertisement,
    }
    return render(request, 'board/advertisement/advertisement_approve.html', context)

board/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..forms import AnswerForm
from ..models import Answer,Question



@login_required(login_url='common:login')
def answer_create(request,question_id):
    """
    pybo 답변 등록
    """
    question =get_object_or_404(Question,pk=question_id)
    if request.method =='POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('board:detail',question_id=question.id),answer.id)) # 앵커 엘리먼트
    else:
        form = AnswerForm()
    context = {'question':question,'form':form}
    return render(request,'board/question_detail.html',context)

@login_required(login_url='common:login')
def answer_modify(request,answer_id):
    """pybo 답변수정"""
    answer = get_object_or_404(Answer,pk = answer_id)
    if request.user != answer.author:
        messages.error(request,'수정권한이 없습니다.')
        return redirect('board:detail',question_id = answer.question.id)
    
    if request.method=="POST":
        form = AnswerForm(request.POST,instance = answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('board:detail',question_id=answer.question.id),answer.id))
    else:
        form = AnswerForm(instance = answer)
    context = {'answer':answer,'form':form}
    return render(request,'board/answer_form.html',context)


@login_required(login_url='common:login')
def answer_delete(request,answer_id):
    answer = get_object_or_404(Answer,pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('board:detail',question_id = answer.question.id)

board/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from ..models import Question,Advertisement
from django.utils import timezone
from django.db.models import F



def index(request):
    now = timezone.now()

    # 광고 영역 (문제 없음)
    active_advertisements = (
    Advertisement.objects
    .select_related("question", "question__author", "question__category")
    .filter(
        status='approved',
        start_date__lte=now,
        end_date__gte=now
        )
    )

    hero_advertisement = (
    active_advertisements
    .filter(main_banner__isnull=False, main_poster=True)
    .first()
    )

    main_advertisements = (
        active_advertisements
        .filter(main_banner__isnull=False)
        .exclude(main_poster=True)
        .order_by('order')
    )

    side_advertisements = (
        active_advertisements
        .filter(side_banner__isnull=False)
        .exclude(main_poster=True)
        .order_by('order')
    )


    # 1. 인기 게시글 (N+1 제거)
    hot_posts = list(Question.objects
    .select_related("category", "author")
    .prefetch_related("up_voter")
    .annotate(
        voter_count=Count("up_voter", distinct=True),
        answer_count=Count("answer", distinct=True)
    )
    .filter(
        create_date__gte=now - timezone.timedelta(days=31),
        category__type__in=["board", "story"]
    )
        .order_by("-voter_count")[:10]
    )

    government_news = list(Question.objects
        .select_related("category", "author")
        .annotate(answer_count=Count("answer"))
        .filter(category__slug="gov")
        .order_by("-create_date")[:5]
    )

    business_trends = list(Question.objects
        .select_related("category", "author")
        .annotate(answer_count=Count("answer"))
        .filter(category__slug="trend")
        .order_by("-create_date")[:5]
    )

    main_advertisements = list(main_advertisements)
    side_advertisements = list(side_advertisements)

    context = {
        "hero_advertisement": hero_advertisement,
        "main_advertisements": main_advertisements,
        "side_advertisements": side_advertisements,
        "hot_posts": hot_posts,
        "government_news": government_news,
        "business_trends": business_trends,
    }

    return render(request, "board/main.html", context)



def detail(request,question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    
    # 조회수 부분
    if not request.session.get('viewed_questions'):
        request.session['viewed_questions'] = []
        
    if question_id not in request.session['viewed_questions']:
        # F() 표현식을 사용하여 race condition 방지
        Question.objects.filter(pk=question_id).update(view_count=F('view_count') + 1)
        request.session['viewed_questions'].append(question_id)
        request.session.modified = True
    question.refresh_from_db()
        
    # bread_crumb부분
    current_category = request.session.get('current_category', question.category.slug)
    context = {
        'question': question,
        'current_category': current_category,
        'current_type' : question.category.type,
    }
    return render(request, 'board/question_detail.html', context)


def faq(request):
    return render(request,'board/faq.html')


def privacy_law(request):
    if request.GET.get('modal') == '1':
        return render(request, 'board/partials/privacy_law_modal.html')
    return render(request,'board/privacy-law.html')

def using_rule(request):
    if request.GET.get('modal') == '1':
        return render(request, 'board/partials/using_rule_modal.html')
    return render(request,'board/using_rule.html')

templates/board/message/conversation_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid px-0 h-100 d-flex flex-column" style="max-height: calc(100vh - 100px);">
    <!-- Chat Header -->
    <div class="card-custom mb-3 flex-shrink-0">
        <div class="card-header-custom d-flex justify-content-between align-items-center py-3">
            <div class="d-flex align-items-center gap-3">
                <a href="{% url 'board:message_list' %}" class="btn btn-sm btn-outline-custom border-0 p-1">
                    <i class="bi bi-arrow-left fs-5"></i>
                </a>
                <div class="d-flex align-items-center gap-2">
                    <div class="rounded-circle bg-light d-flex align-items-center justify-content-center border" style="width: 40px; height: 40px;">
                        <i class="fas fa-user text-secondary"></i>
                    </div>
                    <div>
                        <h6 class="mb-0 fw-bold">{{ other_user.username }}</h6>
                        <div class="dropdown d-inline-block">
                            <a href="#" class="text-muted small text-decoration-none dropdown-toggle" data-bs-toggle="dropdown">
                                옵션
                            </a>
                            <ul class="dropdown-menu shadow-sm border-0 text-small">
                                <li><a class="dropdown-item" href="{% url 'common:user_profile' username=other_user.username %}">프로필 보기</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item text-danger" href="#" onclick="showReportDialog('{{ other_user.username }}'); return false;">신고하기</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Chat Messages Area -->
    <div class="card-custom flex-grow-1 overflow-hidden d-flex flex-column shadow-sm">
        <div class="card-body p-4 messages-container overflow-auto" style="background-color: #f8fafc;">
            {% for message in message_list %}
            <div class="d-flex mb-3 {% if message.sender == request.user %}justify-content-end{% else %}justify-content-start{% endif %}">
                {% if message.sender != request.user %}
                <div class="flex-shrink-0 me-2 mt-1">
                    <div class="rounded-circle bg-white d-flex align-items-center justify-content-center border shadow-sm" style="width: 32px; height: 32px;">
                        <i class="fas fa-user text-secondary small"></i>
                    </div>
                </div>
                {% endif %}
                
                <div class="d-flex flex-column {% if message.sender == request.user %}align-items-end{% else %}align-items-start{% endif %}" style="max-width: 75%;">
                    <div class="p-3 rounded-3 shadow-sm text-break 
                        {% if message.sender == request.user %}
                        bg-primary text-white rounded-top-right-0
                        {% else %}
                        bg-white text-dark border rounded-top-left-0
                        {% endif %}">
                        {{ message.content|linebreaksbr }}
                    </div>
                    <small class="text-muted mt-1" style="font-size: 0.7rem;">{{ message.created_at|date:"m/d H:i" }}</small>
                </div>
            </div>
            {% endfor %}
        </div>

        <!-- Input Area -->
        <div class="card-footer bg-white border-top p-3">
            <form method="post" action="{% url 'board:send_message' %}" class="d-flex gap-2">
                {% csrf_token %}
                <input type="hidden" name="receiver" value="{{ other_user.username }}">
                <textarea name="content" class="form-control form-control-custom bg-light border-0" 
                          rows="1" placeholder="메시지를 입력하세요..." required style="resize: none; min-height: 42px;"></textarea>
                <button type="submit" class="btn btn-primary-custom px-4">
                    <i class="bi bi-send-fill"></i>
                </button>
            </form>
        </div>
    </div>
</div>

<style>
    .rounded-top-right-0 { border-top-right-radius: 0 !important; }
    .rounded-top-left-0 { border-top-left-radius: 0 !important; }
    
    /* Custom Scrollbar for Chat */
    .messages-container::-webkit-scrollbar {
        width: 6px;
    }
    .messages-container::-webkit-scrollbar-track {
        background: transparent;
    }
    .messages-container::-webkit-scrollbar-thumb {
        background-color: rgba(0,0,0,0.1);
        border-radius: 3px;
    }
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const container = document.querySelector('.messages-container');
    container.scrollTop = container.scrollHeight;
    
    // Auto-resize textarea
    const textarea = document.querySelector('textarea[name="content"]');
    textarea.addEventListener('input', function() {
        this.style.height = 'auto';
        this.style.height = (this.scrollHeight) + 'px';
        if(this.value === '') this.style.height = '42px';
    });
    
    // Submit on Enter (without Shift)
    textarea.addEventListener('keydown', function(e) {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            this.form.submit();
        }
    });
});
</script>
{% endblock %}

templates/board/message/message_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid px-0">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-custom shadow-sm">
                <div class="card-header-custom bg-white border-bottom py-3 d-flex justify-content-between align-items-center">
                    <h5 class="mb-0 fw-bold">
                        {% if request.user == message.receiver %}
                            <span class="text-muted small me-2">From.</span>{{ message.sender.username }}
                        {% else %}
                            <span class="text-muted small me-2">To.</span>{{ message.receiver.username }}
                        {% endif %}
                    </h5>
                    <small class="text-muted">{{ message.created_at|date:"Y.m.d H:i" }}</small>
                </div>
                
                <div class="card-body p-4">
                    <div class="message-content mb-5 p-3 bg-light rounded-3">
                        {{ message.content|linebreaks }}
                    </div>
                    
                    <div class="d-flex justify-content-between">
                        <a href="{% url 'board:message_list' %}" class="btn btn-outline-custom">
                            <i class="bi bi-arrow-left me-1"></i>목록으로
                        </a>
                        {% if request.user == message.receiver %}
                            <a href="{% url 'board:send_message' %}?reply_to={{ message.sender.username }}" 
                               class="btn btn-primary-custom">
                                <i class="bi bi-reply-fill me-1"></i>답장하기
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/board/message/message_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid px-0">
    <!-- Header -->
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h2 class="fw-bold mb-1">메시지함</h2>
            <p class="text-muted small mb-0">주고받은 쪽지 목록입니다.</p>
        </div>
        <a href="{% url 'board:send_message' %}" class="btn btn-primary-custom">
            <i class="bi bi-pencil-square me-2"></i>새 쪽지
        </a>
    </div>

    <!-- Message List -->
    <div class="card-custom shadow-sm">
        <div class="list-group list-group-flush">
            {% for conv in conversations %}
            <a href="{% url 'board:conversation_detail' conv.user.id %}" class="list-group-item list-group-item-action p-3 border-bottom hover-bg-light transition-base">
                <div class="d-flex align-items-center">
                    <!-- User Avatar (Placeholder) -->
                    <div class="flex-shrink-0 me-3">
                        <div class="rounded-circle bg-light d-flex align-items-center justify-content-center border" style="width: 48px; height: 48px;">
                            <i class="fas fa-user text-secondary fa-lg"></i>
                        </div>
                    </div>
                    
                    <!-- Content -->
                    <div class="flex-grow-1 min-w-0">
                        <div class="d-flex justify-content-between align-items-center mb-1">
                            <h6 class="mb-0 fw-bold text-dark d-flex align-items-center gap-2">
                                {{ conv.user.username }}
                                {% if conv.unread_count %}
                                <span class="badge bg-danger rounded-pill" style="font-size: 0.7rem;">{{ conv.unread_count }}</span>
                                {% endif %}
                            </h6>
                            <small class="text-muted" style="font-size: 0.75rem;">{{ conv.last_message.created_at|date:"m.d H:i" }}</small>
                        </div>
                        <p class="mb-0 text-muted text-truncate small {% if conv.unread_count %}fw-medium text-dark{% endif %}">
                            {{ conv.last_message.content }}
                        </p>
                    </div>
                </div>
            </a>
            {% empty %}
            <div class="p-5 text-center text-muted">
                <i class="bi bi-envelope-open fs-1 mb-3 d-block opacity-50"></i>
                <p class="mb-0">주고받은 메시지가 없습니다.</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<style>
    .hover-bg-light:hover {
        background-color: var(--bg-surface-hover);
    }
</style>
{% endblock %}