board/urls.py
from django.urls import path

from .views import base_views,question_views,answer_views,vote_views,category_views,bookmark_views,message_views,search_views,advertise_views,inquiry_views

app_name = 'board'



urlpatterns = [
    # base_views.py
    path('',base_views.index, name = 'index'),
    path('question/<int:question_id>/', base_views.detail, name = 'detail'),
    path('faq/',base_views.faq,name='faq'),
    path('privacy_law/',base_views.privacy_law,name='privacy_law'),
    path('using_rule/',base_views.using_rule,name='using_rule'),
    
    #category_views.py
    path('category/<str:slug>/',category_views.category_questions, name = 'category_questions'),
    path('api/categories/', category_views.get_categories_by_type, name='get_categories_by_type'),
    
    # question_views.py
    path('question/create/', question_views.question_create,name='question_create'),
    path('question/modify/<int:question_id>/',question_views.question_modify,name='question_modify'),
    path('question/delete/<int:question_id>/',question_views.question_delete,name='question_delete'),
    path('question/notice/<int:question_id>/', question_views.toggle_notice, name='toggle_notice'),
    
    path('advertisement/create/<int:question_id>', advertise_views.advertisement_create, name='advertisement_create'),
    path('advertisement/list/', advertise_views.advertisement_list, name='advertisement_list'),
    path('advertisement/modify/<int:question_id>/', advertise_views.advertisement_modify, name='advertisement_modify'),
    path('advertisement/delete/<int:question_id>/', advertise_views.advertisement_delete, name='advertisement_delete'),
    path('advertisement/approve/<int:question_id>/', advertise_views.advertisement_approve, name='advertisement_approve'),
    
    # 좋아요 view
    path('question/<int:question_id>/bookmark/', bookmark_views.bookmark_question, name='bookmark_question'),
    path('questions/bookmarked/',bookmark_views.bookmarked_questions,name='bookmarked_questions'),
    
    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create,name='answer_create'),
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify,name="answer_modify"),
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete,name='answer_delete'),
    
    path('search/', search_views.search, name='search'),
    path('search/<str:category_slug>/', search_views.category_search_results, name='category_search_results'),
    
    #vote_views.py
    path('upvote/question/<int:question_id>/',vote_views.upvote_question,name='upvote_question'),
    path('downvote/question/<int:question_id>/',vote_views.downvote_question,name='downvote_question'),
    path('upvote/answer/<int:answer_id>/',vote_views.upvote_answer,name='upvote_answer'),
    path('downvote/answer/<int:answer_id>/',vote_views.downvote_answer,name='downvote_answer'),

    
    path('messages/', message_views.message_list, name='message_list'),
    path('messages/conversation/<int:user_id>/', message_views.conversation_detail, name='conversation_detail'),
    path('messages/send/', message_views.send_message, name='send_message'),
    path('api/search-users/', message_views.search_users, name='search_users'),
    
    #문의하기
    path('inquiry/', inquiry_views.inquiry_list, name='inquiry_list'),
    path('inquiry/create/', inquiry_views.inquiry_create, name='inquiry_create'),
    path('inquiry/modify/<int:inquiry_id>/', inquiry_views.inquiry_modify, name='inquiry_modify'),
    path('inquiry/delete/<int:inquiry_id>/', inquiry_views.inquiry_delete, name='inquiry_delete'),
    
    path('inquiry/<int:inquiry_id>/', inquiry_views.inquiry_detail, name='inquiry_detail'),
    path('inquiry/<int:inquiry_id>/comment/', inquiry_views.inquiry_comment_create, name='inquiry_comment_create'),
    path('inquiry/comment/modify/<int:comment_id>/', inquiry_views.inquiry_comment_modify, name='inquiry_comment_modify'),
    path('inquiry/comment/delete/<int:comment_id>/', inquiry_views.inquiry_comment_delete, name='inquiry_comment_delete'),

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as av
from django.urls import reverse_lazy
from .views import base_views,find_views,profile_views,admin_views,auth_views,report_views

app_name = 'common'

urlpatterns = [
    # 로그인 & 아웃
    path('login/',auth_views.login_view,name='login'),
    path('logout/',auth_views.logout_view,name='logout'),

    
    path('delete-account/',auth_views.delete_account,name='delete_account'),
    
    # 회원가입 및 메일인증
    path('activate/<str:uidb64>/<str:token>/', base_views.activate, name='activate'),
    path('signup/', base_views.signup, name='signup'),
    path('get_business_types/<int:category_id>/', base_views.get_business_types, name='get_business_types'),
    
    # 프로필 수정
    path('profile/',profile_views.profile,name = 'profile'),
    path('profile/<str:username>/', profile_views.user_profile, name='user_profile'),
    path('password_change/', av.PasswordChangeView.as_view(
        template_name='common/password_change.html',
        success_url='/common/password_change/done/'
    ), name='password_change'),
    path('password_change/done/', av.PasswordChangeDoneView.as_view(
        template_name='common/password_change_done.html'
    ), name='password_change_done'),
    
    path('my-posts/',profile_views.my_posts,name='my_posts'),
    
    # ID/PW 찾기
    path('find_id/', find_views.find_id, name='find_id'),
    path('reset_password/', find_views.reset_password, name='reset_password'),
    path('reset_password_confirm/<uidb64>/<token>/', 
        av.PasswordResetConfirmView.as_view(
            template_name='common/password_reset_confirm.html',
            success_url=reverse_lazy('common:login')
        ),
        name='password_reset_confirm'),
    
# common/urls.py
    path('admin/toggle-notice/<int:question_id>/', admin_views.toggle_notice, name='toggle_notice'),
    path('admin/delete-post/<int:question_id>/', admin_views.admin_delete, name='admin_delete'),
    path('admin/restrict_user/', admin_views.restrict_user, name='restrict_user'),
    path('admin/unrestrict/',admin_views.unrestrict_user,name='unrestrict_user'),
    path('admin/toggle-advertiser/',admin_views.toggle_advertise,name='toggle_advertise'),

    path('ajax/fetch-user-info/', admin_views.fetch_user_info, name='fetch_user_info'),


    path('report/user/<str:username>/', report_views.report_user, name='report_user'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('common/',include('common.urls')),
    path('',base_views.index,name='index'),
    path('summernote/', include('django_summernote.urls')),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    # urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)) ]
    urlpatterns += [
        path('silk/', include('silk.urls', namespace='silk'))
    ]

board/views/advertise_views.py
from django.shortcuts import render, get_object_or_404,redirect
from ..models import Question, Advertisement
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from ..forms import AdvertisementForm,AdvertisementApprovalForm
from django.contrib import messages


@login_required(login_url='common:login')
def advertisement_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    if request.user != question.author or not request.user.is_advertise:
        raise PermissionDenied('광고 등록 권한이 없습니다.')
    
    if request.method == 'POST':
        form = AdvertisementForm(request.POST, request.FILES)
        if form.is_valid():
            advertisement = form.save(commit=False)
            advertisement.question = question
            advertisement.save()
            messages.success(request, '광고가 신청되었습니다. 관리자 승인 후 게시됩니다.')
            return redirect('board:detail', question_id=question.id)
    else:
        form = AdvertisementForm()
    
    context = {
        'form': form,
        'question': question
    }
    return render(request, 'board/advertisement/advertisement_form.html', context)


@login_required(login_url='common:login')
def advertisement_modify(request, question_id):
    advertisement = get_object_or_404(Advertisement, question_id=question_id)
    
    if request.user != advertisement.question.author and not request.user.is_admin:
        raise PermissionDenied('수정 권한이 없습니다.')
        
    if request.method == "POST":
        form = AdvertisementForm(request.POST, request.FILES, instance=advertisement)
        if form.is_valid():
            advertisement = form.save()
            return redirect('board:detail', question_id=question_id)
    else:
        form = AdvertisementForm(instance=advertisement)
    
    context = {
        'form': form,
        'question': advertisement.question
    }
    return render(request, 'board/advertisement/advertisement_form.html', context)


@login_required(login_url='common:login')
def advertisement_delete(request, question_id):
    advertisement = get_object_or_404(Advertisement, question_id=question_id)
    
    if request.user != advertisement.question.author and not request.user.is_admin:
        raise PermissionDenied('삭제 권한이 없습니다.')
    
    if request.method == "POST":
        advertisement.delete()
        messages.success(request, '광고가 삭제되었습니다.')
        return redirect('board:detail', question_id=question_id)
    
    return render(request, 'board/advertisement/advertisement_confirm_delete.html', {
        'advertisement': advertisement
    })

@login_required(login_url='common:login')
def advertisement_list(request):
    # 일반 광고주는 자신의 광고만, 관리자는 모든 광고 조회
    if request.user.is_admin:
        advertisements = Advertisement.objects.all()
    else:
        advertisements = Advertisement.objects.filter(question__author=request.user)
        
    context = {'advertisements': advertisements}
    return render(request, 'board/advertisement/advertisement_list.html', context)

@login_required(login_url='common:login')
def advertisement_approve(request, question_id):
    # question_id로 Advertisement 찾기
    advertisement = get_object_or_404(Advertisement, question_id=question_id)
    
    if not request.user.is_admin:
        raise PermissionDenied('관리자만 접근 가능합니다.')
    
    if request.method == 'POST':
        form = AdvertisementApprovalForm(request.POST, instance=advertisement)
        if form.is_valid():
            advertisement = form.save()
            messages.success(request, '광고 상태가 업데이트되었습니다.')
            return redirect('board:advertisement_list')
    else:
        form = AdvertisementApprovalForm(instance=advertisement)
    
    context = {
        'form': form,
        'advertisement': advertisement,
    }
    return render(request, 'board/advertisement/advertisement_approve.html', context)

board/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..forms import AnswerForm
from ..models import Answer,Question



@login_required(login_url='common:login')
def answer_create(request,question_id):
    """
    pybo 답변 등록
    """
    question =get_object_or_404(Question,pk=question_id)
    if request.method =='POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('board:detail',question_id=question.id),answer.id)) # 앵커 엘리먼트
    else:
        form = AnswerForm()
    context = {'question':question,'form':form}
    return render(request,'board/question_detail.html',context)

@login_required(login_url='common:login')
def answer_modify(request,answer_id):
    """pybo 답변수정"""
    answer = get_object_or_404(Answer,pk = answer_id)
    if request.user != answer.author:
        messages.error(request,'수정권한이 없습니다.')
        return redirect('board:detail',question_id = answer.question.id)
    
    if request.method=="POST":
        form = AnswerForm(request.POST,instance = answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('board:detail',question_id=answer.question.id),answer.id))
    else:
        form = AnswerForm(instance = answer)
    context = {'answer':answer,'form':form}
    return render(request,'board/answer_form.html',context)


@login_required(login_url='common:login')
def answer_delete(request,answer_id):
    answer = get_object_or_404(Answer,pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('board:detail',question_id = answer.question.id)

board/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from ..models import Question,Advertisement
from django.utils import timezone
from django.db.models import F



def index(request):
    now = timezone.now()

    # 광고 영역 (문제 없음)
    active_advertisements = (
    Advertisement.objects
    .select_related("question", "question__author", "question__category")
    .filter(
        status='approved',
        start_date__lte=now,
        end_date__gte=now
        )
    )

    hero_advertisement = (
    active_advertisements
    .filter(main_banner__isnull=False, main_poster=True)
    .first()
    )

    main_advertisements = (
        active_advertisements
        .filter(main_banner__isnull=False)
        .exclude(main_poster=True)
        .order_by('order')
    )

    side_advertisements = (
        active_advertisements
        .filter(side_banner__isnull=False)
        .exclude(main_poster=True)
        .order_by('order')
    )


    # 1. 인기 게시글 (N+1 제거)
    hot_posts = list(Question.objects
    .select_related("category", "author")
    .prefetch_related("up_voter")
    .annotate(
        voter_count=Count("up_voter", distinct=True),
        answer_count=Count("answer", distinct=True)
    )
    .filter(
        create_date__gte=now - timezone.timedelta(days=31),
        category__type__in=["board", "story"]
    )
        .order_by("-voter_count")[:10]
    )

    government_news = list(Question.objects
        .select_related("category", "author")
        .annotate(answer_count=Count("answer"))
        .filter(category__slug="gov")
        .order_by("-create_date")[:5]
    )

    business_trends = list(Question.objects
        .select_related("category", "author")
        .annotate(answer_count=Count("answer"))
        .filter(category__slug="trend")
        .order_by("-create_date")[:5]
    )

    main_advertisements = list(main_advertisements)
    side_advertisements = list(side_advertisements)

    context = {
        "hero_advertisement": hero_advertisement,
        "main_advertisements": main_advertisements,
        "side_advertisements": side_advertisements,
        "hot_posts": hot_posts,
        "government_news": government_news,
        "business_trends": business_trends,
    }

    return render(request, "board/main.html", context)



def detail(request,question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    
    # 조회수 부분
    if not request.session.get('viewed_questions'):
        request.session['viewed_questions'] = []
        
    if question_id not in request.session['viewed_questions']:
        # F() 표현식을 사용하여 race condition 방지
        Question.objects.filter(pk=question_id).update(view_count=F('view_count') + 1)
        request.session['viewed_questions'].append(question_id)
        request.session.modified = True
    question.refresh_from_db()
        
    # bread_crumb부분
    current_category = request.session.get('current_category', question.category.slug)
    context = {
        'question': question,
        'current_category': current_category,
        'current_type' : question.category.type,
    }
    return render(request, 'board/question_detail.html', context)


def faq(request):
    return render(request,'board/faq.html')


def privacy_law(request):
    if request.GET.get('modal') == '1':
        return render(request, 'board/partials/privacy_law_modal.html')
    return render(request,'board/privacy-law.html')

def using_rule(request):
    if request.GET.get('modal') == '1':
        return render(request, 'board/partials/using_rule_modal.html')
    return render(request,'board/using_rule.html')

templates/board/inquiry/inquiry_comment_form.html
<!-- templates/board/inquiry_comment_form.html -->
{% extends "base.html" %}
{% block content %}
<div class="container my-4">
    <h5 class="my-3 border-bottom pb-2">답변 수정</h5>
    <form method="post">
        {% csrf_token %}
        {{ form.media }}
        
        {% if form.errors %}
        <div class="alert alert-danger">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

        <div class="form-group mb-3">
            {{ form.content }}
        </div>

        <button type="submit" class="btn btn-primary">수정완료</button>
        <a href="{% url 'board:inquiry_detail' inquiry.id %}" class="btn btn-secondary">취소</a>
    </form>
</div>
{% endblock %}

{% block script %}
<script>
$(document).ready(function() {
    $('#content').summernote({
        height: 300,
        maxFileSize: 20 * 1024 * 1024,
        callbacks: {
            onImageUploadError: function(msg) {
                if (msg === 'File is too large') {
                    alert('이미지 크기는 20MB를 초과할 수 없습니다.');
                }
            }
        }
    });
});
</script>
{% endblock %}

templates/board/inquiry/inquiry_detail.html
{% extends "base.html" %}
{% load board_filter %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">

<div class="container my-4">
    {% if messages %}
    <div class="alert alert-danger my-3">
        {% for message in messages %}
            <strong>{{message.tags}}</strong>
            <ul><li>{{message.message}}</li></ul>
        {% endfor %}
    </div>
    {% endif %}

    <!-- 문의글 영역 -->
    <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h4 class="mb-0">{{ inquiry.subject }}</h4>
            <div class="d-flex align-items-center gap-3">
                <div class="username-action">
                    <span>{{ inquiry.author.username }}</span>
                    <div class="username-dropdown">
                        <a href="{% url 'common:user_profile' username=inquiry.author.username %}">프로필 보기</a>
                        {% if user.is_authenticated and user != inquiry.author %}
                            <a href="{% url 'board:send_message' %}?receiver={{ inquiry.author.username }}">쪽지 보내기</a>
                        {% endif %}
                    </div>
                </div>
                <span class="text-muted">{{ inquiry.created_at|date:"Y.m.d H:i" }}</span>
            </div>
        </div>
        <div class="card-body">
            <div class="mb-4">{{ inquiry.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if request.user == inquiry.author %}
                <div>
                    <a href="{% url 'board:inquiry_modify' inquiry.id %}" 
                       class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary" 
                       data-uri="{% url 'board:inquiry_delete' inquiry.id %}">삭제</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- 답변 목록 -->
    <div class="mb-3">
        <h5 class="border-bottom pb-2">답변 {{inquiry.comments.count}}개</h5>
    </div>

    {% for comment in inquiry.comments.all %}
    <div class="card mb-3">
        <div class="card-body">
            <div class="mb-3">{{comment.content|mark}}</div>
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center gap-3">
                    <div class="text-muted small">
                        <div class="username-action">
                            <span class="badge bg-primary">관리자</span>
                            <span>{{ comment.author.username }}</span>
                        </div>
                        {{ comment.created_at|date:"Y.m.d H:i" }}
                        {% if comment.modified_at and comment.modified_at != comment.created_at %}
                            <span class="text-muted">(수정됨)</span>
                        {% endif %}
                    </div>
                </div>
                {% if user.is_admin %}
                <div>
                    <a href="{% url 'board:inquiry_comment_modify' comment.id %}" 
                        class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary" 
                        data-uri="{% url 'board:inquiry_comment_delete' comment.id %}">삭제</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 관리자 답변 폼 -->
    {% if user.is_admin %}
    <form method="post" action="{% url 'board:inquiry_comment_create' inquiry.id %}" class="card">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <div class="card-body">
            <div class="mb-3">
                {{ form.content }}
            </div>
            <div class="text-end">
                <button type="submit" class="btn btn-primary">답변 등록</button>
            </div>
        </div>
    </form>
    {% endif %}

    <div class="mt-3">
        <a href="{% url 'board:inquiry_list' %}" class="btn btn-secondary">목록으로</a>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
$(document).ready(function(){
    $('.delete').on('click', function(e) {
        e.preventDefault();
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>

{% endblock %}

templates/board/inquiry/inquiry_form.html
<!-- templates/board/inquiry_form.html -->
{% extends "base.html" %}
{% block content %}
<div class="container my-4">
    <div class="inquiry-form-container">
        <div class="form-header">
            <h2>문의하기</h2>
            <p class="text-muted">궁금하신 점을 작성해주세요.</p>
        </div>

        <form method="post">
            {% csrf_token %}
            {{ form.media }}
            
            {% if form.errors %}
            <div class="alert alert-danger">
                {% for field in form %}
                    {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}

            <div class="form-group mb-4">
                <label for="subject">제목</label>
                <input type="text" name="subject" id="subject" class="form-control"
                       value="{{ form.subject.value|default_if_none:'' }}"
                       placeholder="제목을 입력해주세요">
            </div>
            
            <div class="form-group mb-4">
                <label for="content">내용</label>
                {{ form.content }}
            </div>

            <div class="button-group">
                <button type="submit" class="btn btn-primary">문의하기</button>
                <a href="javascript:history.back()" class="btn btn-outline-secondary">취소</a>
            </div>
        </form>
    </div>
</div>


{% endblock %}

{% block script %}
<script>
$(document).ready(function() {
    $('#content').summernote({
        height: 300,
        maxFileSize: 5 * 1024 * 1024,
        callbacks: {
            onImageUploadError: function(msg) {
                if (msg === 'File is too large') {
                    alert('이미지 크기는 5MB를 초과할 수 없습니다.');
                }
            }
        }
    });
});
</script>
{% endblock %}

templates/board/inquiry/inquiry_list.html
<!-- templates/inquiry/inquiry_list.html -->
{% extends "base.html" %}
{% load board_filter %}
{% block content %}
<div class="container my-4">
    <div class="row justify-content-between mb-4">
        <div class="col">
            <h2>문의 내역</h2>
        </div>
        <div class="col-auto">
            <a href="{% url 'board:inquiry_create' %}" class="btn btn-primary">
                <i class="bi bi-plus-circle me-1"></i>문의하기
            </a>
        </div>
    </div>

    <div class="inquiry-list">
        {% for inquiry in inquiries %}
        <a href="{% url 'board:inquiry_detail' inquiry.id %}" class="inquiry-item">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-start">
                        <div class="inquiry-content">
                            <h5 class="card-title">{{ inquiry.subject }}</h5>
                            <p class="card-text text-muted">{{ inquiry.content|truncatechars:100|mark }}</p>
                        </div>
                        {% if inquiry.is_answered %}
                        <span class="badge bg-success status-badge">답변완료</span>
                        {% else %}
                        <span class="badge bg-secondary status-badge">답변대기</span>
                        {% endif %}
                    </div>
                    <div class="inquiry-meta">
                        <span class="author">{{ inquiry.author.username }}</span>
                        <span class="date">{{ inquiry.created_at|date:"Y.m.d" }}</span>
                    </div>
                </div>
            </div>
        </a>
        {% empty %}
        <div class="empty-state">
            <i class="bi bi-inbox text-muted mb-3" style="font-size: 2rem;"></i>
            <p>등록된 문의가 없습니다.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}